name: check

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '48 20 * * 4'

env:
  # Make sure cargo commands not only fail on hard errors but also on warnings
  # so we do not accidentally miss newly introduced warnings.
  RUSTFLAGS: -D warnings

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup toolchain install stable
      - run: rustup run stable cargo fmt --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup toolchain install stable
      - run: rustup run stable cargo clippy --all

  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup toolchain install stable
      - run: rustup run stable cargo test
